name: Test on PR

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test infra on PR
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
<<<<<<< HEAD
<<<<<<< HEAD
          aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build Lambda package
        run: |
          sh scripts/build_lambda_package.sh
          
      - name: IaC Apply
        env:
=======
        aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: IaC Apply
      env:
>>>>>>> b9c67797180a7b812e13766cfa0c8c497799f4ff
=======
        aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: IaC Apply
      env:
>>>>>>> b9c67797180a7b812e13766cfa0c8c497799f4ff
          COMMAND_IAC: terraform
      run: |
        cd infrastructure 
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC plan
